<?php
/**
 * TokenEndpointsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  Stardust\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stardust API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Stardust\Core\Stardust\Core\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Stardust\Core\ApiException;
use Stardust\Core\Configuration;
use Stardust\Core\HeaderSelector;
use Stardust\Core\ObjectSerializer;

/**
 * TokenEndpointsApi Class Doc Comment
 *
 * @category Class
 * @package  Stardust\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TokenEndpointsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'tokenBurnPost' => [
            'application/json',
        ],
        'tokenGetGet' => [
            'application/json',
        ],
        'tokenMintBulkPost' => [
            'application/json',
        ],
        'tokenMutatePut' => [
            'application/json',
        ],
        'tokenPropsRemoveDelete' => [
            'application/json',
        ],
        'tokenTransferPost' => [
            'application/json',
        ],
        'tokenWithdrawPost' => [
            'application/json',
        ],
    ];

/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation tokenBurnPost
     *
     * Burn Token
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenBurnRequest $sd_token_burn_request sd_token_burn_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenBurnPost'] to see the possible values for this operation
     *
     * @throws \Stardust\Core\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object|\Stardust\Core\Stardust\Core\Model\Error
     */
    public function tokenBurnPost($sd_token_burn_request, string $contentType = self::contentTypes['tokenBurnPost'][0])
    {
        list($response) = $this->tokenBurnPostWithHttpInfo($sd_token_burn_request, $contentType);
        return $response;
    }

    /**
     * Operation tokenBurnPostWithHttpInfo
     *
     * Burn Token
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenBurnRequest $sd_token_burn_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenBurnPost'] to see the possible values for this operation
     *
     * @throws \Stardust\Core\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object|\Stardust\Core\Stardust\Core\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function tokenBurnPostWithHttpInfo($sd_token_burn_request, string $contentType = self::contentTypes['tokenBurnPost'][0])
    {
        $request = $this->tokenBurnPostRequest($sd_token_burn_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('object' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('object' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Stardust\Core\Stardust\Core\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Stardust\Core\Stardust\Core\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Stardust\Core\Stardust\Core\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'object';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Stardust\Core\Stardust\Core\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation tokenBurnPostAsync
     *
     * Burn Token
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenBurnRequest $sd_token_burn_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenBurnPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tokenBurnPostAsync($sd_token_burn_request, string $contentType = self::contentTypes['tokenBurnPost'][0])
    {
        return $this->tokenBurnPostAsyncWithHttpInfo($sd_token_burn_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation tokenBurnPostAsyncWithHttpInfo
     *
     * Burn Token
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenBurnRequest $sd_token_burn_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenBurnPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tokenBurnPostAsyncWithHttpInfo($sd_token_burn_request, string $contentType = self::contentTypes['tokenBurnPost'][0])
    {
        $returnType = 'object';
        $request = $this->tokenBurnPostRequest($sd_token_burn_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'tokenBurnPost'
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenBurnRequest $sd_token_burn_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenBurnPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function tokenBurnPostRequest($sd_token_burn_request, string $contentType = self::contentTypes['tokenBurnPost'][0])
    {

        // verify the required parameter 'sd_token_burn_request' is set
        if ($sd_token_burn_request === null || (is_array($sd_token_burn_request) && count($sd_token_burn_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sd_token_burn_request when calling tokenBurnPost'
            );
        }


        $resourcePath = '/token/burn';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($sd_token_burn_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($sd_token_burn_request));
            } else {
                $httpBody = $sd_token_burn_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation tokenGetGet
     *
     * Get Token
     *
     * @param  string $token_ids Stringify Array of token ids (ex. &#39;[3589, 3580]&#39;) (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenGetGet'] to see the possible values for this operation
     *
     * @throws \Stardust\Core\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \Stardust\Core\Stardust\Core\Model\SDTokenGetResponse[]|\Stardust\Core\Stardust\Core\Model\Error
     */
    public function tokenGetGet($token_ids, string $contentType = self::contentTypes['tokenGetGet'][0])
    {
        list($response) = $this->tokenGetGetWithHttpInfo($token_ids, $contentType);
        return $response;
    }

    /**
     * Operation tokenGetGetWithHttpInfo
     *
     * Get Token
     *
     * @param  string $token_ids Stringify Array of token ids (ex. &#39;[3589, 3580]&#39;) (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenGetGet'] to see the possible values for this operation
     *
     * @throws \Stardust\Core\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \Stardust\Core\Stardust\Core\Model\SDTokenGetResponse[]|\Stardust\Core\Stardust\Core\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function tokenGetGetWithHttpInfo($token_ids, string $contentType = self::contentTypes['tokenGetGet'][0])
    {
        $request = $this->tokenGetGetRequest($token_ids, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\Stardust\Core\Stardust\Core\Model\SDTokenGetResponse[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Stardust\Core\Stardust\Core\Model\SDTokenGetResponse[]' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Stardust\Core\Stardust\Core\Model\SDTokenGetResponse[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Stardust\Core\Stardust\Core\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Stardust\Core\Stardust\Core\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Stardust\Core\Stardust\Core\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\Stardust\Core\Stardust\Core\Model\SDTokenGetResponse[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Stardust\Core\Stardust\Core\Model\SDTokenGetResponse[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Stardust\Core\Stardust\Core\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation tokenGetGetAsync
     *
     * Get Token
     *
     * @param  string $token_ids Stringify Array of token ids (ex. &#39;[3589, 3580]&#39;) (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenGetGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tokenGetGetAsync($token_ids, string $contentType = self::contentTypes['tokenGetGet'][0])
    {
        return $this->tokenGetGetAsyncWithHttpInfo($token_ids, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation tokenGetGetAsyncWithHttpInfo
     *
     * Get Token
     *
     * @param  string $token_ids Stringify Array of token ids (ex. &#39;[3589, 3580]&#39;) (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenGetGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tokenGetGetAsyncWithHttpInfo($token_ids, string $contentType = self::contentTypes['tokenGetGet'][0])
    {
        $returnType = '\Stardust\Core\Stardust\Core\Model\SDTokenGetResponse[]';
        $request = $this->tokenGetGetRequest($token_ids, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'tokenGetGet'
     *
     * @param  string $token_ids Stringify Array of token ids (ex. &#39;[3589, 3580]&#39;) (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenGetGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function tokenGetGetRequest($token_ids, string $contentType = self::contentTypes['tokenGetGet'][0])
    {

        // verify the required parameter 'token_ids' is set
        if ($token_ids === null || (is_array($token_ids) && count($token_ids) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token_ids when calling tokenGetGet'
            );
        }


        $resourcePath = '/token/get';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $token_ids,
            'tokenIds', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation tokenMintBulkPost
     *
     * Mint Tokens
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenMintBulkRequest $sd_token_mint_bulk_request sd_token_mint_bulk_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenMintBulkPost'] to see the possible values for this operation
     *
     * @throws \Stardust\Core\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return int[]|\Stardust\Core\Stardust\Core\Model\Error
     */
    public function tokenMintBulkPost($sd_token_mint_bulk_request, string $contentType = self::contentTypes['tokenMintBulkPost'][0])
    {
        list($response) = $this->tokenMintBulkPostWithHttpInfo($sd_token_mint_bulk_request, $contentType);
        return $response;
    }

    /**
     * Operation tokenMintBulkPostWithHttpInfo
     *
     * Mint Tokens
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenMintBulkRequest $sd_token_mint_bulk_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenMintBulkPost'] to see the possible values for this operation
     *
     * @throws \Stardust\Core\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of int[]|\Stardust\Core\Stardust\Core\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function tokenMintBulkPostWithHttpInfo($sd_token_mint_bulk_request, string $contentType = self::contentTypes['tokenMintBulkPost'][0])
    {
        $request = $this->tokenMintBulkPostRequest($sd_token_mint_bulk_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('int[]' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('int[]' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'int[]', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Stardust\Core\Stardust\Core\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Stardust\Core\Stardust\Core\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Stardust\Core\Stardust\Core\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'int[]';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'int[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Stardust\Core\Stardust\Core\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation tokenMintBulkPostAsync
     *
     * Mint Tokens
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenMintBulkRequest $sd_token_mint_bulk_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenMintBulkPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tokenMintBulkPostAsync($sd_token_mint_bulk_request, string $contentType = self::contentTypes['tokenMintBulkPost'][0])
    {
        return $this->tokenMintBulkPostAsyncWithHttpInfo($sd_token_mint_bulk_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation tokenMintBulkPostAsyncWithHttpInfo
     *
     * Mint Tokens
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenMintBulkRequest $sd_token_mint_bulk_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenMintBulkPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tokenMintBulkPostAsyncWithHttpInfo($sd_token_mint_bulk_request, string $contentType = self::contentTypes['tokenMintBulkPost'][0])
    {
        $returnType = 'int[]';
        $request = $this->tokenMintBulkPostRequest($sd_token_mint_bulk_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'tokenMintBulkPost'
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenMintBulkRequest $sd_token_mint_bulk_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenMintBulkPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function tokenMintBulkPostRequest($sd_token_mint_bulk_request, string $contentType = self::contentTypes['tokenMintBulkPost'][0])
    {

        // verify the required parameter 'sd_token_mint_bulk_request' is set
        if ($sd_token_mint_bulk_request === null || (is_array($sd_token_mint_bulk_request) && count($sd_token_mint_bulk_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sd_token_mint_bulk_request when calling tokenMintBulkPost'
            );
        }


        $resourcePath = '/token/mint-bulk';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($sd_token_mint_bulk_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($sd_token_mint_bulk_request));
            } else {
                $httpBody = $sd_token_mint_bulk_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation tokenMutatePut
     *
     * Mutate Token
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenMutateRequest $sd_token_mutate_request sd_token_mutate_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenMutatePut'] to see the possible values for this operation
     *
     * @throws \Stardust\Core\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object|\Stardust\Core\Stardust\Core\Model\Error
     */
    public function tokenMutatePut($sd_token_mutate_request, string $contentType = self::contentTypes['tokenMutatePut'][0])
    {
        list($response) = $this->tokenMutatePutWithHttpInfo($sd_token_mutate_request, $contentType);
        return $response;
    }

    /**
     * Operation tokenMutatePutWithHttpInfo
     *
     * Mutate Token
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenMutateRequest $sd_token_mutate_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenMutatePut'] to see the possible values for this operation
     *
     * @throws \Stardust\Core\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object|\Stardust\Core\Stardust\Core\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function tokenMutatePutWithHttpInfo($sd_token_mutate_request, string $contentType = self::contentTypes['tokenMutatePut'][0])
    {
        $request = $this->tokenMutatePutRequest($sd_token_mutate_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('object' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('object' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Stardust\Core\Stardust\Core\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Stardust\Core\Stardust\Core\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Stardust\Core\Stardust\Core\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'object';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Stardust\Core\Stardust\Core\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation tokenMutatePutAsync
     *
     * Mutate Token
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenMutateRequest $sd_token_mutate_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenMutatePut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tokenMutatePutAsync($sd_token_mutate_request, string $contentType = self::contentTypes['tokenMutatePut'][0])
    {
        return $this->tokenMutatePutAsyncWithHttpInfo($sd_token_mutate_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation tokenMutatePutAsyncWithHttpInfo
     *
     * Mutate Token
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenMutateRequest $sd_token_mutate_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenMutatePut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tokenMutatePutAsyncWithHttpInfo($sd_token_mutate_request, string $contentType = self::contentTypes['tokenMutatePut'][0])
    {
        $returnType = 'object';
        $request = $this->tokenMutatePutRequest($sd_token_mutate_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'tokenMutatePut'
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenMutateRequest $sd_token_mutate_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenMutatePut'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function tokenMutatePutRequest($sd_token_mutate_request, string $contentType = self::contentTypes['tokenMutatePut'][0])
    {

        // verify the required parameter 'sd_token_mutate_request' is set
        if ($sd_token_mutate_request === null || (is_array($sd_token_mutate_request) && count($sd_token_mutate_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sd_token_mutate_request when calling tokenMutatePut'
            );
        }


        $resourcePath = '/token/mutate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($sd_token_mutate_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($sd_token_mutate_request));
            } else {
                $httpBody = $sd_token_mutate_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation tokenPropsRemoveDelete
     *
     * Remove Token Property
     *
     * @param  string $token_id Token Id returned from token/create (ex. 5) (required)
     * @param  string $props Stringify Array of token mutable property names ex: &#39;[\&quot;exp\&quot;, \&quot;health\&quot;]&#39; } (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenPropsRemoveDelete'] to see the possible values for this operation
     *
     * @throws \Stardust\Core\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object|\Stardust\Core\Stardust\Core\Model\Error
     */
    public function tokenPropsRemoveDelete($token_id, $props, string $contentType = self::contentTypes['tokenPropsRemoveDelete'][0])
    {
        list($response) = $this->tokenPropsRemoveDeleteWithHttpInfo($token_id, $props, $contentType);
        return $response;
    }

    /**
     * Operation tokenPropsRemoveDeleteWithHttpInfo
     *
     * Remove Token Property
     *
     * @param  string $token_id Token Id returned from token/create (ex. 5) (required)
     * @param  string $props Stringify Array of token mutable property names ex: &#39;[\&quot;exp\&quot;, \&quot;health\&quot;]&#39; } (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenPropsRemoveDelete'] to see the possible values for this operation
     *
     * @throws \Stardust\Core\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object|\Stardust\Core\Stardust\Core\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function tokenPropsRemoveDeleteWithHttpInfo($token_id, $props, string $contentType = self::contentTypes['tokenPropsRemoveDelete'][0])
    {
        $request = $this->tokenPropsRemoveDeleteRequest($token_id, $props, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('object' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('object' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Stardust\Core\Stardust\Core\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Stardust\Core\Stardust\Core\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Stardust\Core\Stardust\Core\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'object';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Stardust\Core\Stardust\Core\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation tokenPropsRemoveDeleteAsync
     *
     * Remove Token Property
     *
     * @param  string $token_id Token Id returned from token/create (ex. 5) (required)
     * @param  string $props Stringify Array of token mutable property names ex: &#39;[\&quot;exp\&quot;, \&quot;health\&quot;]&#39; } (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenPropsRemoveDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tokenPropsRemoveDeleteAsync($token_id, $props, string $contentType = self::contentTypes['tokenPropsRemoveDelete'][0])
    {
        return $this->tokenPropsRemoveDeleteAsyncWithHttpInfo($token_id, $props, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation tokenPropsRemoveDeleteAsyncWithHttpInfo
     *
     * Remove Token Property
     *
     * @param  string $token_id Token Id returned from token/create (ex. 5) (required)
     * @param  string $props Stringify Array of token mutable property names ex: &#39;[\&quot;exp\&quot;, \&quot;health\&quot;]&#39; } (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenPropsRemoveDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tokenPropsRemoveDeleteAsyncWithHttpInfo($token_id, $props, string $contentType = self::contentTypes['tokenPropsRemoveDelete'][0])
    {
        $returnType = 'object';
        $request = $this->tokenPropsRemoveDeleteRequest($token_id, $props, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'tokenPropsRemoveDelete'
     *
     * @param  string $token_id Token Id returned from token/create (ex. 5) (required)
     * @param  string $props Stringify Array of token mutable property names ex: &#39;[\&quot;exp\&quot;, \&quot;health\&quot;]&#39; } (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenPropsRemoveDelete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function tokenPropsRemoveDeleteRequest($token_id, $props, string $contentType = self::contentTypes['tokenPropsRemoveDelete'][0])
    {

        // verify the required parameter 'token_id' is set
        if ($token_id === null || (is_array($token_id) && count($token_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $token_id when calling tokenPropsRemoveDelete'
            );
        }

        // verify the required parameter 'props' is set
        if ($props === null || (is_array($props) && count($props) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $props when calling tokenPropsRemoveDelete'
            );
        }


        $resourcePath = '/token/props-remove';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $token_id,
            'tokenId', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $props,
            'props', // param base name
            'string', // openApiType
            '', // style
            false, // explode
            true // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation tokenTransferPost
     *
     * Transfer Tokens
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenTransferRequest $sd_token_transfer_request sd_token_transfer_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenTransferPost'] to see the possible values for this operation
     *
     * @throws \Stardust\Core\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object|\Stardust\Core\Stardust\Core\Model\Error
     */
    public function tokenTransferPost($sd_token_transfer_request, string $contentType = self::contentTypes['tokenTransferPost'][0])
    {
        list($response) = $this->tokenTransferPostWithHttpInfo($sd_token_transfer_request, $contentType);
        return $response;
    }

    /**
     * Operation tokenTransferPostWithHttpInfo
     *
     * Transfer Tokens
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenTransferRequest $sd_token_transfer_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenTransferPost'] to see the possible values for this operation
     *
     * @throws \Stardust\Core\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object|\Stardust\Core\Stardust\Core\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function tokenTransferPostWithHttpInfo($sd_token_transfer_request, string $contentType = self::contentTypes['tokenTransferPost'][0])
    {
        $request = $this->tokenTransferPostRequest($sd_token_transfer_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('object' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('object' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Stardust\Core\Stardust\Core\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Stardust\Core\Stardust\Core\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Stardust\Core\Stardust\Core\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'object';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Stardust\Core\Stardust\Core\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation tokenTransferPostAsync
     *
     * Transfer Tokens
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenTransferRequest $sd_token_transfer_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenTransferPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tokenTransferPostAsync($sd_token_transfer_request, string $contentType = self::contentTypes['tokenTransferPost'][0])
    {
        return $this->tokenTransferPostAsyncWithHttpInfo($sd_token_transfer_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation tokenTransferPostAsyncWithHttpInfo
     *
     * Transfer Tokens
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenTransferRequest $sd_token_transfer_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenTransferPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tokenTransferPostAsyncWithHttpInfo($sd_token_transfer_request, string $contentType = self::contentTypes['tokenTransferPost'][0])
    {
        $returnType = 'object';
        $request = $this->tokenTransferPostRequest($sd_token_transfer_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'tokenTransferPost'
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenTransferRequest $sd_token_transfer_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenTransferPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function tokenTransferPostRequest($sd_token_transfer_request, string $contentType = self::contentTypes['tokenTransferPost'][0])
    {

        // verify the required parameter 'sd_token_transfer_request' is set
        if ($sd_token_transfer_request === null || (is_array($sd_token_transfer_request) && count($sd_token_transfer_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sd_token_transfer_request when calling tokenTransferPost'
            );
        }


        $resourcePath = '/token/transfer';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($sd_token_transfer_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($sd_token_transfer_request));
            } else {
                $httpBody = $sd_token_transfer_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation tokenWithdrawPost
     *
     * Withdraw Token
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenWithdrawRequest $sd_token_withdraw_request sd_token_withdraw_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenWithdrawPost'] to see the possible values for this operation
     *
     * @throws \Stardust\Core\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object|\Stardust\Core\Stardust\Core\Model\Error
     */
    public function tokenWithdrawPost($sd_token_withdraw_request, string $contentType = self::contentTypes['tokenWithdrawPost'][0])
    {
        list($response) = $this->tokenWithdrawPostWithHttpInfo($sd_token_withdraw_request, $contentType);
        return $response;
    }

    /**
     * Operation tokenWithdrawPostWithHttpInfo
     *
     * Withdraw Token
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenWithdrawRequest $sd_token_withdraw_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenWithdrawPost'] to see the possible values for this operation
     *
     * @throws \Stardust\Core\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object|\Stardust\Core\Stardust\Core\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function tokenWithdrawPostWithHttpInfo($sd_token_withdraw_request, string $contentType = self::contentTypes['tokenWithdrawPost'][0])
    {
        $request = $this->tokenWithdrawPostRequest($sd_token_withdraw_request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('object' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('object' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, 'object', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 500:
                    if ('\Stardust\Core\Stardust\Core\Model\Error' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\Stardust\Core\Stardust\Core\Model\Error' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\Stardust\Core\Stardust\Core\Model\Error', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = 'object';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 500:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\Stardust\Core\Stardust\Core\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation tokenWithdrawPostAsync
     *
     * Withdraw Token
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenWithdrawRequest $sd_token_withdraw_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenWithdrawPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tokenWithdrawPostAsync($sd_token_withdraw_request, string $contentType = self::contentTypes['tokenWithdrawPost'][0])
    {
        return $this->tokenWithdrawPostAsyncWithHttpInfo($sd_token_withdraw_request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation tokenWithdrawPostAsyncWithHttpInfo
     *
     * Withdraw Token
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenWithdrawRequest $sd_token_withdraw_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenWithdrawPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function tokenWithdrawPostAsyncWithHttpInfo($sd_token_withdraw_request, string $contentType = self::contentTypes['tokenWithdrawPost'][0])
    {
        $returnType = 'object';
        $request = $this->tokenWithdrawPostRequest($sd_token_withdraw_request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'tokenWithdrawPost'
     *
     * @param  \Stardust\Core\Stardust\Core\Model\SDTokenWithdrawRequest $sd_token_withdraw_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['tokenWithdrawPost'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function tokenWithdrawPostRequest($sd_token_withdraw_request, string $contentType = self::contentTypes['tokenWithdrawPost'][0])
    {

        // verify the required parameter 'sd_token_withdraw_request' is set
        if ($sd_token_withdraw_request === null || (is_array($sd_token_withdraw_request) && count($sd_token_withdraw_request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sd_token_withdraw_request when calling tokenWithdrawPost'
            );
        }


        $resourcePath = '/token/withdraw';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($sd_token_withdraw_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($sd_token_withdraw_request));
            } else {
                $httpBody = $sd_token_withdraw_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('x-api-key');
        if ($apiKey !== null) {
            $headers['x-api-key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
