<?php
/**
 * SDOrderGetResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Stardust\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stardust API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Stardust\Core\Stardust\Core\Model;

use \ArrayAccess;
use \Stardust\Core\ObjectSerializer;

/**
 * SDOrderGetResponse Class Doc Comment
 *
 * @category Class
 * @package  Stardust\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SDOrderGetResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SDOrderGetResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'offered_by' => 'string',
        'accepted_by' => 'string',
        'tokens_requested' => '\Stardust\Core\Stardust\Core\Model\SDOrderGetAllResponseTokensRequestedInner[]',
        'tokens_offered' => '\Stardust\Core\Stardust\Core\Model\SDOrderGetAllResponseTokensRequestedInner[]',
        'status' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'offered_by' => null,
        'accepted_by' => null,
        'tokens_requested' => null,
        'tokens_offered' => null,
        'status' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'offered_by' => false,
		'accepted_by' => false,
		'tokens_requested' => false,
		'tokens_offered' => false,
		'status' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'offered_by' => 'offeredBy',
        'accepted_by' => 'acceptedBy',
        'tokens_requested' => 'tokensRequested',
        'tokens_offered' => 'tokensOffered',
        'status' => 'status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'offered_by' => 'setOfferedBy',
        'accepted_by' => 'setAcceptedBy',
        'tokens_requested' => 'setTokensRequested',
        'tokens_offered' => 'setTokensOffered',
        'status' => 'setStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'offered_by' => 'getOfferedBy',
        'accepted_by' => 'getAcceptedBy',
        'tokens_requested' => 'getTokensRequested',
        'tokens_offered' => 'getTokensOffered',
        'status' => 'getStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('offered_by', $data ?? [], null);
        $this->setIfExists('accepted_by', $data ?? [], null);
        $this->setIfExists('tokens_requested', $data ?? [], null);
        $this->setIfExists('tokens_offered', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['offered_by'] === null) {
            $invalidProperties[] = "'offered_by' can't be null";
        }
        if ($this->container['accepted_by'] === null) {
            $invalidProperties[] = "'accepted_by' can't be null";
        }
        if ($this->container['tokens_requested'] === null) {
            $invalidProperties[] = "'tokens_requested' can't be null";
        }
        if ($this->container['tokens_offered'] === null) {
            $invalidProperties[] = "'tokens_offered' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets offered_by
     *
     * @return string
     */
    public function getOfferedBy()
    {
        return $this->container['offered_by'];
    }

    /**
     * Sets offered_by
     *
     * @param string $offered_by The playerId who initiated the order
     *
     * @return self
     */
    public function setOfferedBy($offered_by)
    {
        if (is_null($offered_by)) {
            throw new \InvalidArgumentException('non-nullable offered_by cannot be null');
        }
        $this->container['offered_by'] = $offered_by;

        return $this;
    }

    /**
     * Gets accepted_by
     *
     * @return string
     */
    public function getAcceptedBy()
    {
        return $this->container['accepted_by'];
    }

    /**
     * Sets accepted_by
     *
     * @param string $accepted_by The playerId who is being offered a order
     *
     * @return self
     */
    public function setAcceptedBy($accepted_by)
    {
        if (is_null($accepted_by)) {
            throw new \InvalidArgumentException('non-nullable accepted_by cannot be null');
        }
        $this->container['accepted_by'] = $accepted_by;

        return $this;
    }

    /**
     * Gets tokens_requested
     *
     * @return \Stardust\Core\Stardust\Core\Model\SDOrderGetAllResponseTokensRequestedInner[]
     */
    public function getTokensRequested()
    {
        return $this->container['tokens_requested'];
    }

    /**
     * Sets tokens_requested
     *
     * @param \Stardust\Core\Stardust\Core\Model\SDOrderGetAllResponseTokensRequestedInner[] $tokens_requested tokens_requested
     *
     * @return self
     */
    public function setTokensRequested($tokens_requested)
    {
        if (is_null($tokens_requested)) {
            throw new \InvalidArgumentException('non-nullable tokens_requested cannot be null');
        }
        $this->container['tokens_requested'] = $tokens_requested;

        return $this;
    }

    /**
     * Gets tokens_offered
     *
     * @return \Stardust\Core\Stardust\Core\Model\SDOrderGetAllResponseTokensRequestedInner[]
     */
    public function getTokensOffered()
    {
        return $this->container['tokens_offered'];
    }

    /**
     * Sets tokens_offered
     *
     * @param \Stardust\Core\Stardust\Core\Model\SDOrderGetAllResponseTokensRequestedInner[] $tokens_offered tokens_offered
     *
     * @return self
     */
    public function setTokensOffered($tokens_offered)
    {
        if (is_null($tokens_offered)) {
            throw new \InvalidArgumentException('non-nullable tokens_offered cannot be null');
        }
        $this->container['tokens_offered'] = $tokens_offered;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status The status of the order ['offer', 'accepted', 'cancelled']
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


