<?php
/**
 * SDTemplateGetResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Stardust\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stardust API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Stardust\Core\Stardust\Core\Model;

use \ArrayAccess;
use \Stardust\Core\ObjectSerializer;

/**
 * SDTemplateGetResponse Class Doc Comment
 *
 * @category Class
 * @package  Stardust\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class SDTemplateGetResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SDTemplateGetResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'game_id' => 'int',
        '_id' => 'int',
        'cap' => 'string',
        'contract_type' => 'string',
        'total_supply' => 'string',
        'name' => 'string',
        'type' => 'string',
        'props' => '\Stardust\Core\Stardust\Core\Model\SDTemplateGetAllResponseProps',
        'public_contract_metadata' => 'object',
        'public_token_metadata' => 'object',
        'fees' => '\Stardust\Core\Stardust\Core\Model\SDGameGetResponseFeesInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'game_id' => null,
        '_id' => null,
        'cap' => null,
        'contract_type' => null,
        'total_supply' => null,
        'name' => null,
        'type' => null,
        'props' => null,
        'public_contract_metadata' => null,
        'public_token_metadata' => null,
        'fees' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'game_id' => false,
		'_id' => false,
		'cap' => false,
		'contract_type' => false,
		'total_supply' => false,
		'name' => false,
		'type' => false,
		'props' => false,
		'public_contract_metadata' => false,
		'public_token_metadata' => false,
		'fees' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'game_id' => 'gameId',
        '_id' => '_id',
        'cap' => 'cap',
        'contract_type' => 'contractType',
        'total_supply' => 'totalSupply',
        'name' => 'name',
        'type' => 'type',
        'props' => 'props',
        'public_contract_metadata' => 'publicContractMetadata',
        'public_token_metadata' => 'publicTokenMetadata',
        'fees' => 'fees'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'game_id' => 'setGameId',
        '_id' => 'setId',
        'cap' => 'setCap',
        'contract_type' => 'setContractType',
        'total_supply' => 'setTotalSupply',
        'name' => 'setName',
        'type' => 'setType',
        'props' => 'setProps',
        'public_contract_metadata' => 'setPublicContractMetadata',
        'public_token_metadata' => 'setPublicTokenMetadata',
        'fees' => 'setFees'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'game_id' => 'getGameId',
        '_id' => 'getId',
        'cap' => 'getCap',
        'contract_type' => 'getContractType',
        'total_supply' => 'getTotalSupply',
        'name' => 'getName',
        'type' => 'getType',
        'props' => 'getProps',
        'public_contract_metadata' => 'getPublicContractMetadata',
        'public_token_metadata' => 'getPublicTokenMetadata',
        'fees' => 'getFees'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const CONTRACT_TYPE_ERC721 = 'ERC721';
    public const CONTRACT_TYPE_INTERNAL_MINT = 'internal-mint';
    public const CONTRACT_TYPE_EXTERNAL_NO_MINT = 'external-no-mint';
    public const TYPE_FT = 'FT';
    public const TYPE_NFT = 'NFT';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getContractTypeAllowableValues()
    {
        return [
            self::CONTRACT_TYPE_ERC721,
            self::CONTRACT_TYPE_INTERNAL_MINT,
            self::CONTRACT_TYPE_EXTERNAL_NO_MINT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTypeAllowableValues()
    {
        return [
            self::TYPE_FT,
            self::TYPE_NFT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('game_id', $data ?? [], null);
        $this->setIfExists('_id', $data ?? [], null);
        $this->setIfExists('cap', $data ?? [], null);
        $this->setIfExists('contract_type', $data ?? [], null);
        $this->setIfExists('total_supply', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('props', $data ?? [], null);
        $this->setIfExists('public_contract_metadata', $data ?? [], null);
        $this->setIfExists('public_token_metadata', $data ?? [], null);
        $this->setIfExists('fees', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['game_id'] === null) {
            $invalidProperties[] = "'game_id' can't be null";
        }
        if (($this->container['game_id'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'game_id', must be smaller than or equal to 2147483647.";
        }

        if (($this->container['game_id'] < 0)) {
            $invalidProperties[] = "invalid value for 'game_id', must be bigger than or equal to 0.";
        }

        if ($this->container['_id'] === null) {
            $invalidProperties[] = "'_id' can't be null";
        }
        if (($this->container['_id'] > 2147483647)) {
            $invalidProperties[] = "invalid value for '_id', must be smaller than or equal to 2147483647.";
        }

        if (($this->container['_id'] < 0)) {
            $invalidProperties[] = "invalid value for '_id', must be bigger than or equal to 0.";
        }

        if ($this->container['cap'] === null) {
            $invalidProperties[] = "'cap' can't be null";
        }
        $allowedValues = $this->getContractTypeAllowableValues();
        if (!is_null($this->container['contract_type']) && !in_array($this->container['contract_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'contract_type', must be one of '%s'",
                $this->container['contract_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['total_supply'] === null) {
            $invalidProperties[] = "'total_supply' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalidProperties[] = "'name' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!is_null($this->container['type']) && !in_array($this->container['type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'type', must be one of '%s'",
                $this->container['type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['props'] === null) {
            $invalidProperties[] = "'props' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets game_id
     *
     * @return int
     */
    public function getGameId()
    {
        return $this->container['game_id'];
    }

    /**
     * Sets game_id
     *
     * @param int $game_id Game ID Number (unsigned 32 bit integer)
     *
     * @return self
     */
    public function setGameId($game_id)
    {
        if (is_null($game_id)) {
            throw new \InvalidArgumentException('non-nullable game_id cannot be null');
        }

        if (($game_id > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $game_id when calling SDTemplateGetResponse., must be smaller than or equal to 2147483647.');
        }
        if (($game_id < 0)) {
            throw new \InvalidArgumentException('invalid value for $game_id when calling SDTemplateGetResponse., must be bigger than or equal to 0.');
        }

        $this->container['game_id'] = $game_id;

        return $this;
    }

    /**
     * Gets _id
     *
     * @return int
     */
    public function getId()
    {
        return $this->container['_id'];
    }

    /**
     * Sets _id
     *
     * @param int $_id _id
     *
     * @return self
     */
    public function setId($_id)
    {
        if (is_null($_id)) {
            throw new \InvalidArgumentException('non-nullable _id cannot be null');
        }

        if (($_id > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $_id when calling SDTemplateGetResponse., must be smaller than or equal to 2147483647.');
        }
        if (($_id < 0)) {
            throw new \InvalidArgumentException('invalid value for $_id when calling SDTemplateGetResponse., must be bigger than or equal to 0.');
        }

        $this->container['_id'] = $_id;

        return $this;
    }

    /**
     * Gets cap
     *
     * @return string
     */
    public function getCap()
    {
        return $this->container['cap'];
    }

    /**
     * Sets cap
     *
     * @param string $cap u96 Number as String, min: 0, max: 39614081257132168796771975167
     *
     * @return self
     */
    public function setCap($cap)
    {
        if (is_null($cap)) {
            throw new \InvalidArgumentException('non-nullable cap cannot be null');
        }
        $this->container['cap'] = $cap;

        return $this;
    }

    /**
     * Gets contract_type
     *
     * @return string|null
     */
    public function getContractType()
    {
        return $this->container['contract_type'];
    }

    /**
     * Sets contract_type
     *
     * @param string|null $contract_type The type of custom contract bieng used for this template.
     *
     * @return self
     */
    public function setContractType($contract_type)
    {
        if (is_null($contract_type)) {
            throw new \InvalidArgumentException('non-nullable contract_type cannot be null');
        }
        $allowedValues = $this->getContractTypeAllowableValues();
        if (!in_array($contract_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'contract_type', must be one of '%s'",
                    $contract_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['contract_type'] = $contract_type;

        return $this;
    }

    /**
     * Gets total_supply
     *
     * @return string
     */
    public function getTotalSupply()
    {
        return $this->container['total_supply'];
    }

    /**
     * Sets total_supply
     *
     * @param string $total_supply u96 Number as String, min: 0, max: 39614081257132168796771975167
     *
     * @return self
     */
    public function setTotalSupply($total_supply)
    {
        if (is_null($total_supply)) {
            throw new \InvalidArgumentException('non-nullable total_supply cannot be null');
        }
        $this->container['total_supply'] = $total_supply;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string $name The name of the template
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $allowedValues = $this->getTypeAllowableValues();
        if (!in_array($type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'type', must be one of '%s'",
                    $type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets props
     *
     * @return \Stardust\Core\Stardust\Core\Model\SDTemplateGetAllResponseProps
     */
    public function getProps()
    {
        return $this->container['props'];
    }

    /**
     * Sets props
     *
     * @param \Stardust\Core\Stardust\Core\Model\SDTemplateGetAllResponseProps $props props
     *
     * @return self
     */
    public function setProps($props)
    {
        if (is_null($props)) {
            throw new \InvalidArgumentException('non-nullable props cannot be null');
        }
        $this->container['props'] = $props;

        return $this;
    }

    /**
     * Gets public_contract_metadata
     *
     * @return object|null
     */
    public function getPublicContractMetadata()
    {
        return $this->container['public_contract_metadata'];
    }

    /**
     * Sets public_contract_metadata
     *
     * @param object|null $public_contract_metadata Returned to marketplaces as contract metadata
     *
     * @return self
     */
    public function setPublicContractMetadata($public_contract_metadata)
    {
        if (is_null($public_contract_metadata)) {
            throw new \InvalidArgumentException('non-nullable public_contract_metadata cannot be null');
        }
        $this->container['public_contract_metadata'] = $public_contract_metadata;

        return $this;
    }

    /**
     * Gets public_token_metadata
     *
     * @return object|null
     */
    public function getPublicTokenMetadata()
    {
        return $this->container['public_token_metadata'];
    }

    /**
     * Sets public_token_metadata
     *
     * @param object|null $public_token_metadata Inherited by tokens, and returned to marketplaces as token metadata
     *
     * @return self
     */
    public function setPublicTokenMetadata($public_token_metadata)
    {
        if (is_null($public_token_metadata)) {
            throw new \InvalidArgumentException('non-nullable public_token_metadata cannot be null');
        }
        $this->container['public_token_metadata'] = $public_token_metadata;

        return $this;
    }

    /**
     * Gets fees
     *
     * @return \Stardust\Core\Stardust\Core\Model\SDGameGetResponseFeesInner[]|null
     */
    public function getFees()
    {
        return $this->container['fees'];
    }

    /**
     * Sets fees
     *
     * @param \Stardust\Core\Stardust\Core\Model\SDGameGetResponseFeesInner[]|null $fees fees
     *
     * @return self
     */
    public function setFees($fees)
    {
        if (is_null($fees)) {
            throw new \InvalidArgumentException('non-nullable fees cannot be null');
        }
        $this->container['fees'] = $fees;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


