<?php
/**
 * SDGameGetResponseFeesInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Stardust\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stardust API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Stardust\Core\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SDGameGetResponseFeesInnerTest Class Doc Comment
 *
 * @category    Class
 * @description SDGameGetResponseFeesInner
 * @package     Stardust\Core
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SDGameGetResponseFeesInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SDGameGetResponseFeesInner"
     */
    public function testSDGameGetResponseFeesInner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fee_percentage"
     */
    public function testPropertyFeePercentage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fee_type"
     */
    public function testPropertyFeeType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
