<?php
/**
 * PlayerEndpointsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Stardust\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stardust API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Stardust\Core\Test\Api;

use \Stardust\Core\Configuration;
use \Stardust\Core\ApiException;
use \Stardust\Core\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PlayerEndpointsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Stardust\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PlayerEndpointsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for playerCountGet
     *
     * Get Player Count.
     *
     */
    public function testPlayerCountGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for playerCreatePost
     *
     * Create Player.
     *
     */
    public function testPlayerCreatePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for playerGetAllGet
     *
     * Get All Players.
     *
     */
    public function testPlayerGetAllGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for playerGetGet
     *
     * Get Player.
     *
     */
    public function testPlayerGetGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for playerGetIdGet
     *
     * Get Player ID.
     *
     */
    public function testPlayerGetIdGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for playerGetIdsGet
     *
     * Get All Player IDs.
     *
     */
    public function testPlayerGetIdsGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for playerGetInventoryGet
     *
     * Get Player Inventory.
     *
     */
    public function testPlayerGetInventoryGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for playerMutatePut
     *
     * Mutate Player.
     *
     */
    public function testPlayerMutatePut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for playerRemoveDelete
     *
     * Remove Player.
     *
     */
    public function testPlayerRemoveDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for playerWalletGetGet
     *
     * Get Player Wallet.
     *
     */
    public function testPlayerWalletGetGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for playerWithdrawPost
     *
     * Withdraw From Player.
     *
     */
    public function testPlayerWithdrawPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
