<?php
/**
 * TemplateEndpointsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Stardust\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stardust API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Stardust\Core\Test\Api;

use \Stardust\Core\Configuration;
use \Stardust\Core\ApiException;
use \Stardust\Core\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TemplateEndpointsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Stardust\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TemplateEndpointsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for templateCountGet
     *
     * Get Template Count.
     *
     */
    public function testTemplateCountGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templateCreatePost
     *
     * Create Template.
     *
     */
    public function testTemplateCreatePost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templateGetAllGet
     *
     * Get All Templates.
     *
     */
    public function testTemplateGetAllGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templateGetGet
     *
     * Get Template.
     *
     */
    public function testTemplateGetGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templateGetTokensGet
     *
     * Get Template Tokens.
     *
     */
    public function testTemplateGetTokensGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templateMutatePut
     *
     * Mutate Template.
     *
     */
    public function testTemplateMutatePut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templatePropsRemoveDelete
     *
     * Remove Template Property.
     *
     */
    public function testTemplatePropsRemoveDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for templateRemoveDelete
     *
     * Remove Template.
     *
     */
    public function testTemplateRemoveDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
