<?php
/**
 * TokenEndpointsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Stardust\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Stardust API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2023-05-08T04:33:59Z
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.5.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Stardust\Core\Test\Api;

use \Stardust\Core\Configuration;
use \Stardust\Core\ApiException;
use \Stardust\Core\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * TokenEndpointsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Stardust\Core
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class TokenEndpointsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for tokenBurnPost
     *
     * Burn Token.
     *
     */
    public function testTokenBurnPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tokenGetGet
     *
     * Get Token.
     *
     */
    public function testTokenGetGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tokenMintBulkPost
     *
     * Mint Tokens.
     *
     */
    public function testTokenMintBulkPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tokenMutatePut
     *
     * Mutate Token.
     *
     */
    public function testTokenMutatePut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tokenPropsRemoveDelete
     *
     * Remove Token Property.
     *
     */
    public function testTokenPropsRemoveDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tokenTransferPost
     *
     * Transfer Tokens.
     *
     */
    public function testTokenTransferPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for tokenWithdrawPost
     *
     * Withdraw Token.
     *
     */
    public function testTokenWithdrawPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
